# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Submit the artifacts (APK and Mapping) to Github"
  lane :releaseGithub do
    Dir.chdir ".." do
      pwd = sh('pwd').strip

      version = sh('grep "version" version.properties | sed -nre \'s/^[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p\'').strip
      last_tag = sh("git describe --abbrev=0 --tags").strip
      this_tag = "v#{version}"

      pretty_format = "### **%s**%n###### %h %an - _%aD_%n%n%b"
      change_log = sh("git log --pretty=format:\"#{pretty_format}\" #{last_tag}..HEAD --no-merges")

      artifacts = []
      artifacts = artifacts.concat(Dir.glob("**/*.apk"))
      artifacts = artifacts.concat(Dir.glob("**/*-mapping.txt"))
      artifacts = artifacts.map { |file| "#{pwd}/#{file}" }

      github_release = set_github_release(
        repository_name: "sodalabs/android-looping-pager-layoutmanager",
        api_token: ENV["GITHUB_API_TOKEN"],
        name: this_tag,
        tag_name: this_tag,
        description: change_log,
        commitish: "master",
        upload_assets: artifacts
      )
    end
  end
end
